### ISSUE TITLE
Сломана либа

### ISSUE THREAD

**Issue by Toxenskiy** [AS7RIDENIED/LOLZTEAM#11]
Первый момент исправить proxies на proxy
![изображение](https://github.com/user-attachments/assets/32fbfac5-bcd3-4910-a367-80deced6c19a)
Делаю два запроса по from_url page=1 и page=2

Получаю такой результат,
```
https://lzt.market/riot/?pmin=50&pmax=99&daybreak=14&knife=1&valorant_region[]=EU&valorant_region[]=NA&inv_min=5000&order_by=pdate_to_down_upload&page=1 40 [147362568, 147362125, 147362314, 147362246, 147334279, 144617757, 144597663, 106268242, 105515442, 100639702, 147356559, 147362139, 147362032, 147362023, 147362145, 147359182, 147359169, 147361918, 147361613, 147361503, 147361439, 147361407, 147283639, 147361225, 147361044, 141378238, 147360876, 147360742, 142698108, 147360319, 147360173, 147360086, 147360057, 147360092, 147359836, 147359918, 147359902, 147359919, 147359822, 147359956]
https://lzt.market/riot/?pmin=50&pmax=99&daybreak=14&knife=1&valorant_region[]=EU&valorant_region[]=NA&inv_min=5000&order_by=pdate_to_down_upload&page=2 40 [147362568, 147362125, 147362314, 147362246, 147334279, 144617757, 144597663, 106268242, 105515442, 100639702, 147356559, 147362139, 147362032, 147362023, 147362145, 147359182, 147359169, 147361918, 147361613, 147361503, 147361439, 147361407, 147283639, 147361225, 147361044, 141378238, 147360876, 147360742, 142698108, 147360319, 147360173, 147360086, 147360057, 147360092, 147359836, 147359918, 147359902, 147359919, 147359822, 147359956]
```

пробовал через params результат другой, но теперь там не те аккаунты, которые могут быть по ссылке которую я указываю

**Comment by Toxenskiy** [comment]
Так же ещё при указании языка "en" результат возвращается на русском, но если поменять на форуме и на маркете язык, то возвращается на английском
Бред

**Comment by AS7RIDENIED** [comment]
httpx ошибку раисает, ибо обновился неделю назад и убрал поддержку параметра. Обновил на proxy
![image](https://github.com/user-attachments/assets/6d61865c-a622-4855-8c0d-87464563f1b0)

httpx оверрайдит параметры в url, если указан params в запросе (Запрос улетал на просто /riot без каких-либо параметров). Пофиксил парсом параметров
Язык ранее не передавался, если парамсы пустые были. Пофиксил
![image](https://github.com/user-attachments/assets/1c0859d1-ee5b-4f8c-ab13-6a63ccd7e489)

**Comment by Toxenskiy** [comment]
и возможно ли добавить параметр currency, чтобы цена товара возвращалась в USD

**Comment by AS7RIDENIED** [comment]
> а почему page=1 в ссылке не работал? просто вчера работало всё, а сегодня уже ничего не работало, хотя либу не обновлял

list.from_url сломан с версии 1.4.6, когда я предефайн сменил с None на {}. Он все параметры игнорировал и page в том числе. Он физически не мог вчера работать, а сегодня нет, если ты либу не обновлял

> и возможно ли добавить параметр currency, чтобы цена товара возвращалась в USD

При поиске так вроде нельзя. Если напрямую получать аккаунт (get /{item_id}), то там маркет вернет extraPrices в котором будут цены в usd+eur. Тут либо самому считать, либо сменить валюту маркета, либо подходящие акки еще раз получать через GET /{item_id}

**Comment by AS7RIDENIED** [comment]
Залил коммит. Можно обновлять https://github.com/AS7RIDENIED/LOLZTEAM/commit/eec2a02287250467e2b20c6d81a9556b6f468236

`pip install LOLZTEAM --upgrade`

**Comment by Toxenskiy** [comment]
так я параметр page в url указывал, не через params и всё было гуд, и сегодня я отправлял запрос, и он обрабатывал же все параметры, но всегда выдавал первый page
но это не важно думаю

**Comment by AS7RIDENIED** [comment]
> так я параметр page в url указывал, не через params и всё было гуд, и сегодня я отправлял запрос, и он обрабатывал же все параметры, но всегда выдавал первый page но это не важно думаю

Я выше писал, но еще раз повторю. Есть у тебя ссылка https://example.url?wasd=qwerty&page=1. Если через httpx отправлять запрос вот так `httpx.get("https://example.url?wasd=qwerty&page=1", params={})` (Именно так он и отправляется в либе начиная с версии 1.4.6), то httpx пересоберет юрл и превратит его из https://example.url?wasd=qwerty&page=1 в https://example.url, т.к в параметрах указан пустой словарь. 
Собственно все параметры указанные в url таким образом и пропали. Чисто физически оно не могло в какой-то момент работать, а в другой нет, если ты либу не обновлял с 1.4.5 на более старшую

**Comment by Toxenskiy** [comment]
хорошо, понял
