### ISSUE TITLE
Market.managing.telegram_reset() doesn't work

### ISSUE THREAD

**Issue by Boirs-k** [AS7RIDENIED/LOLZTEAM#3]
Hello. I'm trying to reset telegram authorizations. When i call market.managing.telegram_reset() i catch an error. LOLZTEAM version  1.2.5

My code:
```python
market = Market(token=my_token, language="en")
response = market.managing.telegram_reset(item_id=my_item_id)
```

Error:
```error
 File "/home/username/.virtualenvs/work_folder/lib/python3.10/site-packages/LOLZTEAM/API.py", line 36, in _send_request
    url = self.base_url + path
TypeError: can only concatenate str (not "dict") to str
```

Same problem with market.managing.telegram(my_item_id) method.

**Comment by AS7RIDENIED** [comment]
Fixed in [v1.2.7](https://github.com/AS7RIDENIED/LOLZTEAM/commit/41e0b9567684190a6664c58ce9cc13a43507fb1d)
Update your library
