### ISSUE TITLE
Market.managing.telegram(item_id)

### ISSUE THREAD

**Issue by Boirs-k** [AS7RIDENIED/LOLZTEAM#4]
Hello. I'm trying to get telegram confirmation code to login to telegram. When i call market.managing.telegram(item_id) that doesn't return dict "codes" how it worked before. In fact i can get code manually from site, but not from api. LOLZTEAM version 1.2.9.

**Comment by AS7RIDENIED** [comment]
> Hello. I'm trying to get telegram confirmation code to login to telegram. When i call market.managing.telegram(item_id) that doesn't return dict "codes" how it worked before. In fact i can get code manually from site, but not from api. LOLZTEAM version 1.2.9.

I don't see a problem. I bought an account and received the codes without any problems. Perhaps you specified the wrong item id?
If you are sure that you have done everything correctly, then you need to create a bug thread here -> [click](https://zelenka.guru/forums/bugs/)
![image](https://github.com/AS7RIDENIED/LOLZTEAM/assets/69326004/5ef2f41c-2650-45bf-bd8d-2c5d538c5df6)

**Comment by Boirs-k** [comment]
> > Hello. I'm trying to get telegram confirmation code to login to telegram. When i call market.managing.telegram(item_id) that doesn't return dict "codes" how it worked before. In fact i can get code manually from site, but not from api. LOLZTEAM version 1.2.9.
> 
> I don't see a problem. I bought an account and received the codes without any problems. Perhaps you specified the wrong item id? If you are sure that you have done everything correctly, then you need to create a bug thread here -> [click](https://zelenka.guru/forums/bugs/) ![image](https://private-user-images.githubusercontent.com/69326004/304882572-5ef2f41c-2650-45bf-bd8d-2c5d538c5df6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODA5MDEsIm5iZiI6MTcwNzk4MDYwMSwicGF0aCI6Ii82OTMyNjAwNC8zMDQ4ODI1NzItNWVmMmY0MWMtMjY1MC00NWJmLWJkOGQtMmM1ZDUzOGM1ZGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA3MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MDZiMWZjYjlhMTM0NTU2YjM4NmYyYjE1MWRkMTRkMDVmM2YwMzllODViZjdiM2M4NDQ1OTVhNjhiMTlkZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zORfrYRr-DK9rzxxebgqXsseLIsiGAqK3A-HoPIPUxY)

Ok, thanks. I've used the same code, but with no .json() converting and it works for a week ago.

**Comment by AS7RIDENIED** [comment]
> Ok, thanks. I've used the same code, but with no .json() converting and it works for a week ago.

**Since version 1.2.0, all methods return a Response object.**

Perhaps you used the LolzteamApi library before, and not LOLZTEAM? (LolzteamApi returns dict by default. Response object is returned there only if it was not possible to convert the response text to dict)
