### ISSUE TITLE
README.md example usage unused imports

### ISSUE THREAD

**Issue by nichind** [AS7RIDENIED/LOLZTEAM#7]
Example usage in README:
```python
from LOLZTEAM import AutoUpdate
from LOLZTEAM import Constants
from LOLZTEAM.API import Forum, Market, Antipublic
from LOLZTEAM.Tweaks import DelaySync, SendAsAsync, CreateJob

token = "your_token"

market = Market(token=token, language="en")
forum = Forum(token=token, language="en")
antipublic = Antipublic(token="Antipublic_key")

DelaySync(apis=[market,forum])
```

Unused imports: `AutoUpdate`, `Constants`, `SendAsAsync`, `CreateJob`

Perhaps they should be removed or an example of use should be added?

**Comment by m1ch4elx** [comment]
> ```python
> from LOLZTEAM import AutoUpdate
> ```

AutoUpdate unused but it updates the library on its import. I guess thats the main reason of this import

**Comment by AS7RIDENIED** [comment]
Долго думал, плакал, радовался, горевал, смеялся и вот наконец решил закрыть данный иссуе...
Пусть там будут всевозможные импорты, во избежание ненужных вопросов мне в лс
